import type { NextPage } from "next";
import Head from "next/head";
import ControlUser from "../container/ControlUser";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Formik Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <ControlUser />
      </div>
    </div>
  );
};

export default Home;
